variables:
  GIT_SUBMODULE_STRATEGY: normal

deploy:
  stage: deploy
  environment: production
  only:
    - master
  tags:
    - ksar
  script:
    - env bash ./prepare_icons.sh
    - pelican content
    - rsync output/ ${PROJECT_PATH} --progress --recursive --ignore-times --checksum --delete --exclude-from=excludex.txt
