
deploy:
  stage: deploy
  environment: production
  only:
    - master
  tags:
    - ksar
  script:
    - git submodule update --init
    - pelican content
    - rsync output/ ${PROJECT_PATH} --recursive --ignore-times --checksum --delete --exclude=.git* --exclude=old-hugo-version
