name: CI

on:
  - push
  - workflow_dispatch

env:
  ARTIFACT_NAME: kubakh-name-files

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout theme
        run: git submodule update --init
      - name: Setup Imagick
        run: sudo apt-get -y install imagemagick
      - name: Prepare icons
        run: ./scripts/prepare_icons.sh
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install vendor libraries
        run: python -m pip install -r requirements.txt
      - name: Compile site files
        run: python -m pelican
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            output
            !output/**/.gitignore
            !output/**/.webassets-cache
  deploy:
    name: Deploy
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: List files
        run: ls -la
