name: CI

on: push

jobs:
  build:
    name: Build artefact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout theme
        run: git submodule update --init
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install vendor libraries
        run: python -m pip install -r requirements.txt
      - name: Compile
        run: python -m pelican
